
# Keras Exercises for Basic Manipulation of Layers, Models, and Loss Functions

This notebook provides a set of exercises designed to familiarize you with the basics of handling layers, models,
and loss functions in Keras, which is essential for working with Large Language Models (LLMs).

## Exercises Overview
1. Creating and Configuring Layers
2. Building Sequential Models
3. Functional API for Model Building
4. Implementing Custom Loss Functions
5. Compiling and Training a Model
6. Freezing Layers in a Model

Each section will include a brief explanation followed by practical exercises.



## 1. Creating and Configuring Layers

**Objective**: Learn how to create and configure different types of layers in Keras.

**Exercises**:
1. Create a Dense layer with 10 neurons and ReLU activation.
2. Create a Dropout layer with a dropout rate of 0.2.
3. Configure a Conv2D layer suitable for input images of shape (28, 28, 1) with 32 filters.


In [1]:
from keras.layers import Dense, Dropout

dense_layer = Dense(10, activation='relu')

In [2]:
import tensorflow as tf
x = tf.constant([[1, 2, 3], [4, 5, 6]])
dense_layer(x)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.        , 1.2546291 , 0.        , 0.5748477 , 3.256651  ,
        1.0953335 , 2.694655  , 0.        , 0.        , 0.6523149 ],
       [0.        , 1.9579749 , 0.        , 0.39932573, 7.609806  ,
        2.432615  , 6.565547  , 0.6803522 , 0.        , 0.21998715]],
      dtype=float32)>

In [5]:
dropout_layer = Dropout(1)
dropout_layer(dense_layer(x))

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0.        , 1.2546291 , 0.        , 0.5748477 , 3.256651  ,
        1.0953335 , 2.694655  , 0.        , 0.        , 0.6523149 ],
       [0.        , 1.9579749 , 0.        , 0.39932573, 7.609806  ,
        2.432615  , 6.565547  , 0.6803522 , 0.        , 0.21998715]],
      dtype=float32)>


## 2. Building Sequential Models

**Objective**: Understand how to build sequential models in Keras.

**Exercises**:
1. Build a sequential model with a Dense layer followed by a Dropout layer.
2. Add a Dense output layer suitable for a classification task with 3 classes.


In [8]:
from keras.models import Sequential

model = Sequential()
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3, activation='softmax'))




In [10]:
model.build(input_shape=(None, 10))

In [11]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dropout_4 (Dropout)         (None, 10)                0         
                                                                 
 dense_4 (Dense)             (None, 3)                 33        
                                                                 
Total params: 143 (572.00 Byte)
Trainable params: 143 (572.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________



## 3. Functional API for Model Building

**Objective**: Learn to use Keras' Functional API for flexible model building.

**Exercises**:
1. Build a simple model with the Functional API using at least two input layers.
2. Create a model that merges two input branches with concatenation.


In [16]:
class MyModel(tf.keras.Model):
  def __init__(self):
    super().__init__()
    self.dense_1 = Dense(128, activation='relu')
    self.dense_2 = Dense(64, activation='relu')
    self.dropout = Dropout(0.2)
    self.dense_3 = Dense(10, activation='softmax')
    self.concat = tf.keras.layers.Concatenate()

  def call(self, inputs):
    x, y = inputs
    x = self.dense_1(x)
    y = self.dense_2(y)
    z = self.concat([x, y])
    x = self.dropout(x)
    return self.dense_3(x), z



In [17]:
model = MyModel()


In [18]:
a = tf.random.normal((2, 10))
b = tf.random.normal((2, 10))
model((a, b))

(<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
 array([[0.08726072, 0.12246495, 0.0990487 , 0.1020054 , 0.1338302 ,
         0.1164879 , 0.06395103, 0.11741704, 0.10731672, 0.05021747],
        [0.06087182, 0.1610275 , 0.08132906, 0.08016706, 0.10888571,
         0.14701955, 0.04061533, 0.10588755, 0.17976364, 0.03443277]],
       dtype=float32)>,
 <tf.Tensor: shape=(2, 192), dtype=float32, numpy=
 array([[0.3006261 , 0.        , 0.        , 0.        , 0.        ,
         0.12359703, 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.2517427 , 0.        , 0.34107152, 0.        , 0.        ,
         0.        , 0.        , 0.04924668, 0.00965034, 0.        ,
         0.22379568, 0.        , 0.33683515, 0.16760264, 0.        ,
         0.26461667, 0.11578378, 0.        , 0.47939268, 0.        ,
         0.38762587, 0.234668  , 0.1368237 , 0.02848465, 0.        ,
         0.        , 0.        , 0.        ,

In [19]:
model.summary()

Model: "my_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             multiple                  1408      
                                                                 
 dense_9 (Dense)             multiple                  704       
                                                                 
 dropout_6 (Dropout)         multiple                  0         
                                                                 
 dense_10 (Dense)            multiple                  1290      
                                                                 
 concatenate_1 (Concatenate  multiple                  0         
 )                                                               
                                                                 
Total params: 3402 (13.29 KB)
Trainable params: 3402 (13.29 KB)
Non-trainable params: 0 (0.00 Byte)
______________________


## 4. Implementing Custom Loss Functions

**Objective**: Implement and understand custom loss functions.

**Exercises**:
1. Write a custom loss function that calculates mean squared error.
2. Implement a custom loss function that adds a regularizing term.



## 5. Compiling and Training a Model

**Objective**: Compile and train a Keras model.

**Exercises**:
1. Compile a model with a specified optimizer, loss function, and metric.
2. Write a code snippet to train a model on given training data and labels.



## 6. Freezing Layers in a Model

**Objective**: Learn to freeze layers during model training.

**Exercises**:
1. Create a model and freeze a specific layer during training.
2. Write an example of training a Keras model while keeping some layers as non-trainable.


In [22]:
model.layers[0].trainable = False

In [23]:
model.summary()

Model: "my_model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_8 (Dense)             multiple                  1408      
                                                                 
 dense_9 (Dense)             multiple                  704       
                                                                 
 dropout_6 (Dropout)         multiple                  0         
                                                                 
 dense_10 (Dense)            multiple                  1290      
                                                                 
 concatenate_1 (Concatenate  multiple                  0         
 )                                                               
                                                                 
Total params: 3402 (13.29 KB)
Trainable params: 1994 (7.79 KB)
Non-trainable params: 1408 (5.50 KB)
______________________