
# TensorFlow 2 Exercises for Basic Tensor Manipulation

This notebook provides a set of exercises designed to familiarize you with the basics of tensor manipulation in TensorFlow 2,
which is essential for handling Large Language Models (LLMs).

## Contents
1. Tensor Basics
2. Tensor Operations
3. Manipulating Tensor Shapes
4. Indexing and Slicing
5. Broadcasting
6. Data Loading and Preprocessing

Each section will include a brief explanation followed by practical exercises.



## 1. Tensor Basics

**Objective**: Understand how to create tensors, and learn about their types and shapes.

**Exercises**:
1. Create a scalar tensor (0-D tensor) with a specific value.
2. Create a 1-D tensor (vector) with 5 elements.
3. Create a 2-D tensor (matrix) of shape (3, 3).
4. Find the data type (`dtype`) of the tensors created above.
5. Convert a numpy array to a TensorFlow tensor.


In [1]:
import tensorflow as tf
tf.constant(5)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [2]:
tf.constant([1,2,3,4,5])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [3]:
import numpy as np

array = np.random.randint(10, size=(3,3))
array

array([[1, 7, 1],
       [7, 1, 8],
       [4, 4, 9]])

In [4]:
tf.constant(array)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 7, 1],
       [7, 1, 8],
       [4, 4, 9]])>

In [5]:
tf.constant(array).dtype

tf.int64


## 2. Tensor Operations

**Objective**: Perform basic arithmetic operations and learn some advanced operations.

**Exercises**:
1. Add, subtract, multiply, and divide two tensors.
2. Compute the mean and standard deviation of a tensor.
3. Apply a non-linear activation function (like ReLU) to a tensor.
4. Perform matrix multiplication between two 2-D tensors.


In [8]:
a = tf.constant([1,3,2,5,6])
b= tf.constant([6,5,3,2, 1])

In [9]:
a + b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([7, 8, 5, 7, 7], dtype=int32)>

In [10]:
a-b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([-5, -2, -1,  3,  5], dtype=int32)>

In [11]:
a*b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 6, 15,  6, 10,  6], dtype=int32)>

In [18]:
a = tf.cast(tf.constant(np.random.randint(10, size=(3,3))), tf.float32)
b = tf.cast(tf.constant(np.random.randint(10, size=(3,3))), tf.float32)
a, b

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 0., 6.],
        [2., 3., 4.],
        [2., 3., 7.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[9., 5., 5.],
        [0., 5., 2.],
        [7., 1., 1.]], dtype=float32)>)

In [20]:
tf.reduce_mean(a, axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.3333333, 3.       , 4.       ], dtype=float32)>

In [21]:
tf.math.reduce_std(a, axis=1)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.6246693, 0.8164966, 2.1602468], dtype=float32)>

In [22]:
tf.matmul(a, b)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[51., 11., 11.],
       [46., 29., 20.],
       [67., 32., 23.]], dtype=float32)>

In [24]:
tf.nn.relu(a-3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 3.],
       [0., 0., 1.],
       [0., 0., 4.]], dtype=float32)>


## 3. Manipulating Tensor Shapes

**Objective**: Learn how to reshape and transpose tensors.

**Exercises**:
1. Create a tensor of shape (4, 4), then reshape it to (2, 8).
2. Transpose a 2-D tensor.
3. Flatten a 3-D tensor to a 1-D tensor.


In [26]:
a = tf.constant(np.random.randint(10, size=(4,4)))
a

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[7, 8, 2, 3],
       [1, 2, 9, 5],
       [1, 8, 1, 2],
       [1, 0, 8, 1]])>

In [27]:
tf.reshape(a, (2,8))

<tf.Tensor: shape=(2, 8), dtype=int64, numpy=
array([[7, 8, 2, 3, 1, 2, 9, 5],
       [1, 8, 1, 2, 1, 0, 8, 1]])>

In [29]:
tf.transpose(a)

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[7, 1, 1, 1],
       [8, 2, 8, 0],
       [2, 9, 1, 8],
       [3, 5, 2, 1]])>

In [30]:
tf.reshape(a, -1)

<tf.Tensor: shape=(16,), dtype=int64, numpy=array([7, 8, 2, 3, 1, 2, 9, 5, 1, 8, 1, 2, 1, 0, 8, 1])>


## 4. Indexing and Slicing

**Objective**: Access specific elements or slices of a tensor.

**Exercises**:
1. Extract a specific element from a tensor.
2. Slice a portion of a tensor.
3. Use boolean tensor indexing to filter elements.


In [31]:
a

<tf.Tensor: shape=(4, 4), dtype=int64, numpy=
array([[7, 8, 2, 3],
       [1, 2, 9, 5],
       [1, 8, 1, 2],
       [1, 0, 8, 1]])>

In [33]:
a[1:,1]

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 8, 0])>


## 5. Broadcasting

**Objective**: Understand and apply broadcasting rules in tensor operations.

**Exercises**:
1. Perform an element-wise addition between tensors of different shapes.
2. Broadcast a smaller tensor to match the shape of a larger tensor in an operation.



## 6. Data Loading and Preprocessing

**Objective**: Use `tf.data` for efficient data handling.

**Exercises**:
1. Create a simple dataset using `tf.data.Dataset`.
2. Apply a transformation (like mapping) to the dataset.
3. Batch and shuffle the dataset.


In [34]:
a = tf.constant(np.random.randint(10, size=(10,2)))
a

<tf.Tensor: shape=(10, 2), dtype=int64, numpy=
array([[7, 4],
       [4, 6],
       [9, 7],
       [6, 5],
       [8, 8],
       [3, 1],
       [8, 4],
       [7, 3],
       [9, 2],
       [4, 4]])>

In [35]:
dataset = tf.data.Dataset.from_tensor_slices(a)
dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(2,), dtype=tf.int64, name=None)>

In [36]:
def mapping(x):
  return x**2

In [37]:
dataset_mapped = dataset.map(mapping)
dataset_mapped

<_MapDataset element_spec=TensorSpec(shape=(2,), dtype=tf.int64, name=None)>

In [38]:
batch_size = 2
dataset_batched = dataset_mapped.batch(batch_size)
dataset_batched

<_BatchDataset element_spec=TensorSpec(shape=(None, 2), dtype=tf.int64, name=None)>

In [39]:
for x in dataset_batched:
  print(x)

tf.Tensor(
[[49 16]
 [16 36]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[81 49]
 [36 25]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[64 64]
 [ 9  1]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[64 16]
 [49  9]], shape=(2, 2), dtype=int64)
tf.Tensor(
[[81  4]
 [16 16]], shape=(2, 2), dtype=int64)
